Garage/Models/ProfileSettings.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Garage.Models
{
    public class ProfileSettings
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Username { get; set; }
    }

}

Garage/Controllers/ProfileSettingsController.cs
using Garage.Filters;
using Garage.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Garage.Controllers
{
    [LoginAuthorize]
    public class ProfileSettingsController : Controller
    {
        GarageDB2Entities db = new GarageDB2Entities();
        //
        // GET: /ProfileSettings/
        public ActionResult Settings(string message = null)
        {
            ViewBag.message = null;
            ViewBag.MsgColor = "red";
            var loggedInUsers = (Users)Session["User"];

            ProfileSettings settingsUsers = new ProfileSettings();

            settingsUsers.Id = loggedInUsers.Id;
            settingsUsers.FirstName = loggedInUsers.FirstName;
            settingsUsers.LastName = loggedInUsers.LastName;
            settingsUsers.Username = loggedInUsers.Username;
            settingsUsers.Email = loggedInUsers.Email;

            if (message != null)
            {
                if (message == "Current Password is Incorrect")
                {
                    ViewBag.Message = "Current Password is Incorrect";
                    return View(settingsUsers);
                }
                if (message == "Password do not macht")
                {
                    ViewBag.Message = "New Password and Confirm Password do not macht";
                    return View(settingsUsers);
                }
                else
                {
                    ViewBag.MsgColor = "green";
                    ViewBag.Message = "Change Confirmed";
                    return View(settingsUsers);
                }
            }

            return View(settingsUsers);
        }

        [HttpPost]

        public ActionResult ChangePassword(string oldPassword, string newPassword, string confirmPassword)
        {
            Users users = (Users)Session["User"];
            if (users.Password != oldPassword)
            {
                return RedirectToAction("Settings", new { message = "Current Password Incorrect" });
            }
            if (newPassword != confirmPassword)
            {
                return RedirectToAction("Settings", new { message = "Paswords do not macht" });
            }

            Users dbUsers = db.Users.Find(users.Id);
            dbUsers.Password = newPassword;
            dbUsers.ConfirmPassword = newPassword;
            db.Entry(dbUsers).State = EntityState.Modified;
            db.SaveChanges();
            Session["User"] = dbUsers;
            return RedirectToAction("Settings", new { message = "Change Confirmed" });
        }

        public ActionResult ChangeEmail(string oldPassword, string newMail)
        {
            Users user = (Users)Session["User"];
            if (user.Password != oldPassword)
            {
                return RedirectToAction("Settings", new { message = "Current Password Incorrect" });
            }

            Users dbUser = db.Users.Find(user.Id);
            dbUser.Email = newMail;
            dbUser.ConfirmPassword = user.Password;
            db.Entry(dbUser).State = EntityState.Modified;
            db.SaveChanges();
            Session["User"] = dbUser;
            return RedirectToAction("Settings", new { message = "Change Confirmed" });
        }
	}
}

Garage/Views/ProfileSettings/Settings.cshtml
@model Garage.Models.ProfileSettings

@{
    ViewBag.Title = "Settings";
}


<div class="pro">
    <div class="container row">
        <h3>ProfileSettings</h3>
        @if (ViewBag.Message != null)
        {
            <h4 style="color:@ViewBag.MsgColor">@ViewBag.Message</h4>
        }
        <hr />
        <div class="col-md-4">
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.FirstName)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.FirstName)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.LastName)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.LastName)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Email)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Email)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Username)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Username)
                </dd>
            </dl>

        </div>

        <div class="col-md-2">
            <div class="btn btn-info togglePassForm" style="display:block; width:100%">Change Password</div>
            <br />
            <div class="btn btn-info toggleEmailForm" style="display: block; width: 100%">Change E-Mail</div>
        </div>
        <div class="col-md-3 passForm">
            @using (Html.BeginForm("ChangePassword", "ProfileSettings", FormMethod.Post))
            {
                <h4>Change Password</h4>
                <div class="form-group">
                    @Html.Password("oldPassword", "", new { placeholder = "Current Password", required = "required" })
                </div>
                <div class="form-group">
                    @Html.Password("newPassword", "", new { placeholder = "New Password", required = "required" })
                </div>
                <div class="form-group">
                    @Html.Password("confirmPassword", "", new { placeholder = "Confirm Password", required = "required" })
                </div>
                <div class="form-group">
                    <input type="submit" value="Change Password" class="btn btn-info" />
                </div>
            }
        </div>
        <div class="col-md-3 emailForm">
            @using (Html.BeginForm("ChangeEmail", "ProfileSettings", FormMethod.Post))
            {
                <h4>Change Email</h4>
                <div class="form-group">
                    @Html.Password("oldPassword", "", new { placeholder = "Current Password", required = "required" })
                </div>
                <div class="form-group">
                    @Html.TextBox("newMail", "", new { placeholder = "New E-Mail", required = "required" })
                </div>
                <div class="form-group">
                    <input type="submit" value="Change E-Mail" class="btn btn-info" />
                </div>
            }
        </div>
    </div>
</div>